### ISSUE TITLE
Installation broken since packages not available anymore and tensorflow version not specified

### ISSUE THREAD

**Issue by 1-w** [NOEL-MNI/deepFCD#16]
Installation broken since packages not available anymore and tensorflow version not specified
## Description

antspyx==0.3.5 not available

## Possible Fix

works with the following combination:

antspyx==0.3.8 --only-binary=antspyx
git+https://github.com/ravnoor/atlasreader@master#egg=atlasreader
Theano==1.0.4
keras==2.2.4
h5py==2.10.0
matplotlib==3.5.1
mo-dots==9.147.22086
nibabel==3.2.2
nilearn==0.9.1
numpy==1.18.5
pandas==1.3.5
psutil==5.9.2
scikit-image==0.19.2
scikit-learn==1.0.2
scipy==1.7.3
setproctitle==1.2.3
tabulate==0.9.0
tqdm==4.64.0
xlrd==2.0.1
tensorflow==1.15.5
tensorflow_probability==0.8

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used (e.g. v1.1.1 or commit hash):
* Environment name and version [e.g. Docker (noelmni/deep-fcd:v1.1.2), M1/Intel macOS 11.6.5, Linux (Conda 4.11 w/ Python 3.7)]:
* Hardware (e.g., 4 vCPUs, 16GB RAM, NVIDIA TITAN RTX w/ 24GB VRAM)
* Using GPU or CPU:
* Operating System (OS) and version (if not using the Docker image; e.g. Ubuntu 20.04.3 LTS):
* OS baremetal or virtualized:

**Comment by 1-w** [comment]
Which tensor flow version do you use?

**Comment by ravnoor** [comment]
TensorFlow isn't a hard dependency of the `deepFCD` project. It still runs on the deprecated Theano backend of Keras.

TensorFlow and TensorFlow-Probability are required by the `ANTsPyNet` dependency which is used for brain extraction. It is embedded within the `deepMask` project and is triggered only when preprocessing is done on the CPU (`os.environ.get("BRAIN_MASKING") == "cpu"`), since `deepMask` is resource-efficient only when run on the GPU.

I'll update `deepMask` with the following code so that modules aren't unnecessarily imported:
```
if os.environ.get("BRAIN_MASKING") == "cpu":
    from antspynet.utilities import brain_extraction
```
