### ISSUE TITLE
Wrong lesion labelling

### ISSUE THREAD

**Issue by 1-w** [NOEL-MNI/deepFCD#21]
https://github.com/NOEL-MNI/deepFCD/blob/69ae43e7b180d4f1c54d70c0d5d5be6c98f50b8c/app/utils/post_processor.py#L59C1-L59C57

This should be  `=  label_list[l] `, instead of `] = num_elements_by_lesion[l].astype(np.int)
` right?

**Comment by ravnoor** [comment]
That seems about right. `num_elements_by_lesion[l].astype(np.int)` outputs the size (voxel count) of the putative lesion instead of the sequential label number. I'll push the change in a day or two. Thanks for reporting!

If you're looking to post-process the outputs for reporting, I might suggest looking at [utils/reporting.py](https://github.com/NOEL-MNI/deepFCD/blob/main/app/utils/reporting.py). It's more intuitive and straightforward.
