### ISSUE TITLE
Inquiry Regarding the Extraction of Patches from 3D Co-Registered Images and Linear Registration of FLAIR to T1-weighted Images

### ISSUE THREAD

**Issue by jaysheth09** [NOEL-MNI/deepFCD#22]
## Description
I am currently facing challenges in locating the code for extracting patches from 3D co-registered images and Registration of FLAIR image to T1-weighted image. 
This process for extracting 3D patches involves thresholding FLAIR images by z-normalizing intensities and subsequently discarding the bottom 10 percentile intensities. My primary concern pertains to determining the appropriate threshold value for this operation.

And, code for the Linear Registration of FLAIR to T1-weighted Image.

## Query:
I would greatly appreciate guidance on selecting an optimal threshold value for this operation. Any insights, best practices, or recommended approaches would be invaluable in assisting me with this task.

Your assistance and expertise in addressing this matter would be highly regarded.

**Comment by jaysheth09** [comment]
unable to find code for Extraction of Patches from 3D Co-Registered Images and Linear Registration of FLAIR to T1-weighted Images

**Comment by ravnoor** [comment]
Here are the functions that:
1. sample patches from multimodal MRI and threshold intensities: https://github.com/NOEL-MNI/deepFCD/blob/21dac51a0838518774e775c61a369539f7cdf8ef/app/utils/patch_dataloader.py#L411
2. registration to the stereotaxic space: https://github.com/NOEL-MNI/deepMask/blob/ccabb5fdd5b6408727d073ad60f98ea82e940c6d/app/utils/image_processing.py#L89

**Comment by ravnoor** [comment]
Thresholding z-normalized (w.r.t each patient NOT a database of healthy controls) FLAIR images by discarding the bottom 10 percentile intensities is a heuristic we adopted to limit the number of patches sampled from the white matter.

Since the FCD-II lesions on FLAIR are hyperintense on both gray matter and white matter, the generated mask (after thresholding of z-normalized image) is a pretty good approximation (crude but good enough) of the gray matter.

10 percentile is just a suggestion, and you can choose to go higher or lower depending on the coverage of the gray matter (or neocortex) in the resulting mask.

**Comment by jaysheth09** [comment]
@ravnoor thanks for your support and detailed explanation.
